---
# utility_meter:
utility_energy:
  source: sensor.utility_energy
  cycle: monthly
  net_consumption: true
daily_energy:
  source: sensor.utility_energy
#    name: Daily Energy
  cycle: daily
  tariffs:
    - peak
    - offpeak
monthly_energy:
  source: sensor.utility_energy
  name: Monthly Energy
  cycle: monthly
utility_energy_inst:
  source: sensor.instant_energy_use
  cycle: monthly
  net_consumption: true
